In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("s3://darwin-raildata-mlops/temp-data/combined.csv")

C:\Users\personal\AppData\Local\Temp\ipykernel_25684\2825219830.py:1: DtypeWarning: Columns (21,30,33,35,40,49,52,54,59,68,71,73,78,87,90,99,115,125,137,150,152,161,162,166,167,174,175,185,187,188,198,200,214,215,216,223,227,229,230,231,234,237,240,241,246,247,248,249,250,252,253,254,255,256,257,258,259,260,262,263,264,267,268,270,271,272,275,276,281,282,286,287,288,289,290,291,292,300,307,308,318,319,329,333,334,337,338,339,340,341,342,343,344,345,346,349,350,351,352,353,354,355,356,357,358,359,362,363,364,365,366,367,368,369,370,371,372,375,376,377,378,379,380,381,382,383,384,387,388,389,390,391,392,393,394,395,399,400,401,402,403,408,411,412,419,420,425,426,429,432,438,440,441,442,443,446,450,454,456,457,460,464,468,470,471,472,473,474,475,480,483,484,485,486,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,602,603,604,605,606,607,608,609,610,611,612,613,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,633,634,635,636,637,638,639,640,641,642,643,644,645,646,649,650,651,653,656,657,658,659,660,661,662,663,664,665,667,668,669,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,690,691,692,693,694,695,696,697,698,699,700,701,702,704,705,707,708,709,710,711,712,713,714,715,716,717,718,719,720,722,723,724,725,726,727,728,729,730,731,732,733,734,735,738,741,744,745,746,747,748,749,750,751,752,753,754,755,757,758,759,760,761,762,763,764,765,766,767,768,769,770,772,774,776,777,779,780,781,782,783,784,786,788,790,792,794,796,798,800,802,803,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1065,1066,1067,1068,1069,1070,1073,1074,1075,1076,1077,1078,1079,1080,1081,1084,1085,1086,1087,1088,1089,1090,1091,1092,1095,1096,1099,1102,1103,1104,1106,1107,1108,1109,1110,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1137,1138,1140,1141,1142,1143,1144,1146,1147,1148,1149,1150,1151,1152,1153,1154,1156,1157,1158,1159,1160,1161,1162,1163,1167,1168,1169,1170,1171,1172,1173,1174,1175,1179,1180,1184,1185,1186,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1320,1321,1322,1323,1324,1325,1327,1328,1330,1331,1332,1333,1335,1336,1337,1338,1339,1342,1343,1346,1347,1350,1351,1355,1356,1357,1358,1359,1362,1363,1364,1365,1366,1367,1368,1369,1370,1374,1375,1376,1377,1378,1379,1380,1381,1382,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1397,1398,1399,1400,1401,1402,1403,1404,1407,1408,1409,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1485,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1516,1518,1520,1522,1524,1526,1528,1530,1531,1532,1533,1534,1535,1536,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1746,1747,1748,1749,1750,1751,1752,1753,1754,1756,1757,1760,1761,1762,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1778,1779,1780,1781,1783,1784,1785,1786,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1801,1802,1803,1804,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1819,1820,1821,1822,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1838,1839,1840,1841,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1857,1858,1859,1860,1862,1863,1864,1865,1867,1868,1869,1870,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1886,1887,1888,1889,1891,1892,1893,1894,1895,1896,1899,1900,1901,1902,1903,1904,1905,1908,1909,1910,1911,1912,1913,1914,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1932,1933,1934,1935,1936,1937,1938,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1956,1957,1958,1959,1961,1962,1963,1964,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1980,1981,1982,1983,1984,1985,1988,1989,1990,1991,1993,1994,1995,1996,1998,1999,2000,2001,2003,2004,2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2024,2025,2026,2027,2029,2030,2031,2032,2033,2034,2037,2038,2039,2040,2042,2043,2044,2045,2047,2048,2049,2050,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2066,2067,2068,2069,2071,2072,2073,2074,2076,2077,2078,2079,2081,2082,2083,2084,2086,2087,2088,2089,2091,2092,2093,2094,2095,2096,2097,2098,2101,2102,2103,2105,2106,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2267,2269,2271,2273,2275,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("s3://darwin-raildata-mlops/temp-data/combined.csv")

In [6]:
df.head(10)

,Pport_@xmlns,Pport_ns2,Pport_ns3,Pport_ns4,Pport_ns5,Pport_ns6,Pport_ns7,Pport_ns8,Pport_ns9,Pport_ns10,...,Pport_uR_schedule_OPIP_@act,Pport_uR_TS_Location_17_plat_@conf,Pport_uR_schedule_0_PP_13_@act,Pport_uR_schedule_0_PP_34_@can,Pport_uR_schedule_1_OR_@can,Pport_uR_schedule_1_DT_@can,Pport_uR_association_main_@wtd,Pport_uR_association_main_@ptd,Pport_uR_association_assoc_@wta,Pport_uR_association_assoc_@pta
0,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.columns.unique().tolist()

['Pport_@xmlns',
 'Pport_ns2',
 'Pport_ns3',
 'Pport_ns4',
 'Pport_ns5',
 'Pport_ns6',
 'Pport_ns7',
 'Pport_ns8',
 'Pport_ns9',
 'Pport_ns10',
 'Pport_ns11',
 'Pport_ns12',
 'Pport_@ts',
 'Pport_@version',
 'Pport_uR_@updateOrigin',
 'Pport_uR_TS_@rid',
 'Pport_uR_TS_@uid',
 'Pport_uR_TS_@ssd',
 'Pport_uR_TS_Location_0_@tpl',
 'Pport_uR_TS_Location_0_@wtp',
 'Pport_uR_TS_Location_0_pass_@et',
 'Pport_uR_TS_Location_0_pass_@delayed',
 'Pport_uR_TS_Location_0_pass_@src',
 'Pport_uR_TS_Location_0_length',
 'Pport_uR_TS_Location_1_@tpl',
 'Pport_uR_TS_Location_1_@wta',
 'Pport_uR_TS_Location_1_@wtd',
 'Pport_uR_TS_Location_1_@pta',
 'Pport_uR_TS_Location_1_@ptd',
 'Pport_uR_TS_Location_1_arr_@et',
 'Pport_uR_TS_Location_1_arr_@delayed',
 'Pport_uR_TS_Location_1_arr_@src',
 'Pport_uR_TS_Location_1_dep_@et',
 'Pport_uR_TS_Location_1_dep_@delayed',
 'Pport_uR_TS_Location_1_dep_@src',
 'Pport_uR_TS_Location_1_plat',
 'Pport_uR_TS_Location_1_length',
 'Pport_uR_TS_Location_2_@tpl',
 'Pport_uR_TS_Location_2_@wtp',
 'Pport_uR_TS_Location_2_pass_@et',
 'Pport_uR_TS_Location_2_pass_@delayed',
 'Pport_uR_TS_Location_2_pass_@src',
 'Pport_uR_TS_Location_2_length',
 'Pport_uR_TS_Location_3_@tpl',
 'Pport_uR_TS_Location_3_@wta',
 'Pport_uR_TS_Location_3_@wtd',
 'Pport_uR_TS_Location_3_@pta',
 'Pport_uR_TS_Location_3_@ptd',
 'Pport_uR_TS_Location_3_arr_@et',
 'Pport_uR_TS_Location_3_arr_@delayed',
 'Pport_uR_TS_Location_3_arr_@src',
 'Pport_uR_TS_Location_3_dep_@et',
 'Pport_uR_TS_Location_3_dep_@delayed',
 'Pport_uR_TS_Location_3_dep_@src',
 'Pport_uR_TS_Location_3_plat',
 'Pport_uR_TS_Location_3_length',
 'Pport_uR_TS_Location_4_@tpl',
 'Pport_uR_TS_Location_4_@wtp',
 'Pport_uR_TS_Location_4_pass_@et',
 'Pport_uR_TS_Location_4_pass_@delayed',
 'Pport_uR_TS_Location_4_pass_@src',
 'Pport_uR_TS_Location_4_length',
 'Pport_uR_TS_Location_5_@tpl',
 'Pport_uR_TS_Location_5_@wta',
 'Pport_uR_TS_Location_5_@wtd',
 'Pport_uR_TS_Location_5_@pta',
 'Pport_uR_TS_Location_5_@ptd',
 'Pport_uR_TS_Location_5_arr_@et',
 'Pport_uR_TS_Location_5_arr_@delayed',
 'Pport_uR_TS_Location_5_arr_@src',
 'Pport_uR_TS_Location_5_dep_@et',
 'Pport_uR_TS_Location_5_dep_@delayed',
 'Pport_uR_TS_Location_5_dep_@src',
 'Pport_uR_TS_Location_5_plat',
 'Pport_uR_TS_Location_5_length',
 'Pport_uR_TS_Location_6_@tpl',
 'Pport_uR_TS_Location_6_@wtp',
 'Pport_uR_TS_Location_6_pass_@et',
 'Pport_uR_TS_Location_6_pass_@delayed',
 'Pport_uR_TS_Location_6_pass_@src',
 'Pport_uR_TS_Location_6_length',
 'Pport_uR_TS_Location_7_@tpl',
 'Pport_uR_TS_Location_7_@wta',
 'Pport_uR_TS_Location_7_@wtd',
 'Pport_uR_TS_Location_7_@pta',
 'Pport_uR_TS_Location_7_@ptd',
 'Pport_uR_TS_Location_7_arr_@et',
 'Pport_uR_TS_Location_7_arr_@delayed',
 'Pport_uR_TS_Location_7_arr_@src',
 'Pport_uR_TS_Location_7_dep_@et',
 'Pport_uR_TS_Location_7_dep_@delayed',
 'Pport_uR_TS_Location_7_dep_@src',
 'Pport_uR_TS_Location_7_plat',
 'Pport_uR_TS_Location_7_length',
 'Pport_uR_TS_Location_8_@tpl',
 'Pport_uR_TS_Location_8_@wta',
 'Pport_uR_TS_Location_8_@pta',
 'Pport_uR_TS_Location_8_arr_@et',
 'Pport_uR_TS_Location_8_arr_@wet',
 'Pport_uR_TS_Location_8_arr_@delayed',
 'Pport_uR_TS_Location_8_arr_@src',
 'Pport_uR_TS_Location_8_plat',
 'Pport_uR_TS_Location_8_length',
 'Pport_uR_TS_Location_@tpl',
 'Pport_uR_TS_Location_@wta',
 'Pport_uR_TS_Location_@wtd',
 'Pport_uR_TS_Location_@pta',
 'Pport_uR_TS_Location_@ptd',
 'Pport_uR_TS_Location_arr_@at',
 'Pport_uR_TS_Location_arr_@atClass',
 'Pport_uR_TS_Location_arr_@src',
 'Pport_uR_TS_Location_dep_@et',
 'Pport_uR_TS_Location_dep_@src',
 'Pport_uR_TS_Location_plat_@platsrc',
 'Pport_uR_TS_Location_plat_@conf',
 'Pport_uR_TS_Location_plat_#text',
 'Pport_uR_TS_Location_length',
 'Pport_uR_TS_Location_0_@wta',
 'Pport_uR_TS_Location_0_@wtd',
 'Pport_uR_TS_Location_0_@pta',
 'Pport_uR_TS_Location_0_@ptd',
 'Pport_uR_TS_Location_0_arr_@et',
 'Pport_uR_TS_Location_0_arr_@src',
 'Pport_uR_TS_Location_0_dep_@et',
 'Pport_uR_TS_Location_0_dep_@src',
 'Pport_uR_TS_Location_0_plat',
 'Pport_uR_TS_Location_1_@wtp',
 'Pport_uR_TS_Location_1_pass_@et',
 'Pport_uR_TS_Location_1_pass_@src',
 'Pport_uR_TS_Location_2_@wta',
 'Pport_uR_TS_Location_2_@wtd',
 'Pport_uR_TS_Location_2_@pta',
 'Pport_uR_TS_Location_2_@ptd',
 'Pport_uR_TS_Location_2_arr_@et',
 'Pport_uR_TS_Location_2_arr_@src',
 'Pport_uR_TS_Location_2_dep_@et',
 'Pport_uR_TS_Location_2_dep_@src',
 'Pport_uR_TS_Location_2_plat',
 'Pport_uR_TS_Location_3_@wtp',
 'Pport_uR_TS_Location_3_pass_@et',
 'Pport_uR_TS_Location_3_pass_@src',
 'Pport_uR_TS_Location_4_@wta',
 'Pport_uR_TS_Location_4_@wtd',
 'Pport_uR_TS_Location_4_@pta',
 'Pport_uR_TS_Location_4_@ptd',
 'Pport_uR_TS_Location_4_arr_@et',
 'Pport_uR_TS_Location_4_arr_@src',
 'Pport_uR_TS_Location_4_dep_@et',
 'Pport_uR_TS_Location_4_dep_@src',
 'Pport_uR_TS_Location_4_plat_@platsrc',
 'Pport_uR_TS_Location_4_plat_#text',
 'Pport_uR_TS_Location_5_plat_@platsrc',
 'Pport_uR_TS_Location_5_plat_#text',
 'Pport_uR_TS_Location_6_@wta',
 'Pport_uR_TS_Location_6_@wtd',
 'Pport_uR_TS_Location_6_@pta',
 'Pport_uR_TS_Location_6_@ptd',
 'Pport_uR_TS_Location_6_arr_@et',
 'Pport_uR_TS_Location_6_arr_@src',
 'Pport_uR_TS_Location_6_dep_@et',
 'Pport_uR_TS_Location_6_dep_@src',
 'Pport_uR_TS_Location_6_plat_@platsrc',
 'Pport_uR_TS_Location_6_plat_#text',
 'Pport_uR_TS_Location_7_arr_@wet',
 'Pport_uR_TS_Location_arr_@srcInst',
 'Pport_uR_TS_Location_0_plat_@platsrc',
 'Pport_uR_TS_Location_0_plat_#text',
 'Pport_uR_TS_Location_6_plat',
 'Pport_uR_TS_Location_7_dep_@wet',
 'Pport_uR_TS_Location_8_@wtd',
 'Pport_uR_TS_Location_8_@ptd',
 'Pport_uR_TS_Location_8_dep_@et',
 'Pport_uR_TS_Location_8_dep_@wet',
 'Pport_uR_TS_Location_8_dep_@src',
 'Pport_uR_TS_Location_8_plat_@platsrc',
 'Pport_uR_TS_Location_8_plat_#text',
 'Pport_uR_TS_Location_9_@tpl',
 'Pport_uR_TS_Location_9_@wta',
 'Pport_uR_TS_Location_9_@wtd',
 'Pport_uR_TS_Location_9_@pta',
 'Pport_uR_TS_Location_9_@ptd',
 'Pport_uR_TS_Location_9_arr_@et',
 'Pport_uR_TS_Location_9_arr_@wet',
 'Pport_uR_TS_Location_9_arr_@src',
 'Pport_uR_TS_Location_9_dep_@et',
 'Pport_uR_TS_Location_9_dep_@wet',
 'Pport_uR_TS_Location_9_dep_@src',
 'Pport_uR_TS_Location_9_plat_@platsrc',
 'Pport_uR_TS_Location_9_plat_#text',
 'Pport_uR_TS_Location_9_length',
 'Pport_uR_TS_Location_10_@tpl',
 'Pport_uR_TS_Location_10_@wta',
 'Pport_uR_TS_Location_10_@wtd',
 'Pport_uR_TS_Location_10_@pta',
 'Pport_uR_TS_Location_10_@ptd',
 'Pport_uR_TS_Location_10_arr_@et',
 'Pport_uR_TS_Location_10_arr_@src',
 'Pport_uR_TS_Location_10_dep_@et',
 'Pport_uR_TS_Location_10_dep_@wet',
 'Pport_uR_TS_Location_10_dep_@src',
 'Pport_uR_TS_Location_10_plat',
 'Pport_uR_TS_Location_10_length',
 'Pport_uR_TS_Location_11_@tpl',
 'Pport_uR_TS_Location_11_@wta',
 'Pport_uR_TS_Location_11_@wtd',
 'Pport_uR_TS_Location_11_@pta',
 'Pport_uR_TS_Location_11_@ptd',
 'Pport_uR_TS_Location_11_arr_@et',
 'Pport_uR_TS_Location_11_arr_@src',
 'Pport_uR_TS_Location_11_dep_@et',
 'Pport_uR_TS_Location_11_dep_@src',
 'Pport_uR_TS_Location_11_plat',
 'Pport_uR_TS_Location_11_length',
 'Pport_uR_TS_Location_1_plat_@platsup',
 'Pport_uR_TS_Location_1_plat_#text',
 'Pport_uR_TS_Location_2_arr_@delayed',
 'Pport_uR_TS_Location_2_dep_@delayed',
 'Pport_uR_TS_LateReason',
 'Pport_uR_TS_Location_0_arr_@at',
 'Pport_uR_TS_Location_0_arr_@atClass',
 'Pport_uR_TS_Location_0_arr_@srcInst',
 'Pport_uR_TS_Location_0_plat_@conf',
 'Pport_uR_TS_Location_3_arr_@wet',
 'Pport_uR_TS_Location_3_dep_@wet',
 'Pport_uR_TS_Location_4_plat_@platsup',
 'Pport_uR_TS_Location_4_plat_@cisPlatsup',
 'Pport_uR_TS_Location_5_arr_@wet',
 'Pport_uR_TS_Location_5_dep_@wet',
 'Pport_uR_TS_Location_6_arr_@wet',
 'Pport_uR_TS_Location_1_suppr',
 'Pport_uR_TS_Location_0_dep_@delayed',
 'Pport_uR_TS_Location_3_pass_@delayed',
 'Pport_uR_TS_Location_5_plat_@platsup',
 'Pport_uR_TS_Location_arr_@et',
 'Pport_uR_TS_Location_plat',
 'Pport_uR_TS_Location_1_plat_@platsrc',
 'Pport_uR_TS_Location_1_plat_@conf',
 'Pport_uR_TS_Location_4_plat',
 'Pport_uR_TS_Location_0_plat_@platsup',
 'Pport_uR_TS_Location_2_plat_@platsup',
 'Pport_uR_TS_Location_2_plat_#text',
 'Pport_uR_TS_Location_4_plat_@conf',
 'Pport_uR_TS_Location_2_plat_@platsrc',
 'Pport_uR_TS_Location_10_plat_@platsup',
 'Pport_uR_TS_Location_10_plat_@cisPlatsup',
 'Pport_uR_TS_Location_10_plat_@platsrc',
 'Pport_uR_TS_Location_10_plat_#text',
 'Pport_uR_TS_Location_0_pass_@etmin',
 'Pport_uR_TS_Location_1_dep_@etmin',
 'Pport_uR_TS_Location_2_dep_@etmin',
 'Pport_uR_TS_Location_3_dep_@etmin',
 'Pport_uR_TS_Location_3_plat_@platsrc',
 'Pport_uR_TS_Location_3_plat_#text',
 'Pport_uR_TS_Location_4_arr_@delayed',
 'Pport_uR_TS_Location_4_dep_@etmin',
 'Pport_uR_TS_Location_4_dep_@delayed',
 'Pport_uR_TS_Location_5_dep_@etmin',
 'Pport_uR_TS_Location_6_arr_@delayed',
 'Pport_uR_TS_Location_6_dep_@etmin',
 'Pport_uR_TS_Location_6_dep_@delayed',
 'Pport_uR_TS_Location_7_dep_@etmin',
 'Pport_uR_TS_Location_7_plat_@platsrc',
 'Pport_uR_TS_Location_7_plat_#text',
 'Pport_uR_TS_Location_8_dep_@etmin',
 'Pport_uR_TS_Location_8_dep_@delayed',
 'Pport_uR_TS_Location_9_@wtp',
 'Pport_uR_TS_Location_9_pass_@et',
 'Pport_uR_TS_Location_9_pass_@etmin',
 'Pport_uR_TS_Location_9_pass_@delayed',
 'Pport_uR_TS_Location_9_pass_@src',
 'Pport_uR_TS_Location_10_arr_@delayed',
 'Pport_uR_TS_Location_10_dep_@etmin',
 'Pport_uR_TS_Location_10_dep_@delayed',
 'Pport_uR_TS_Location_11_@wtp',
 'Pport_uR_TS_Location_11_pass_@et',
 'Pport_uR_TS_Location_11_pass_@etmin',
 'Pport_uR_TS_Location_11_pass_@delayed',
 'Pport_uR_TS_Location_11_pass_@src',
 'Pport_uR_TS_Location_12_@tpl',
 'Pport_uR_TS_Location_12_@wtp',
 'Pport_uR_TS_Location_12_pass_@et',
 'Pport_uR_TS_Location_12_pass_@etmin',
 'Pport_uR_TS_Location_12_pass_@delayed',
 'Pport_uR_TS_Location_12_pass_@src',
 'Pport_uR_TS_Location_12_length',
 'Pport_uR_TS_Location_13_@tpl',
 'Pport_uR_TS_Location_13_@wta',
 'Pport_uR_TS_Location_13_@pta',
 'Pport_uR_TS_Location_13_arr_@et',
 'Pport_uR_TS_Location_13_arr_@etmin',
 'Pport_uR_TS_Location_13_arr_@delayed',
 'Pport_uR_TS_Location_13_arr_@src',
 'Pport_uR_TS_Location_13_plat',
 'Pport_uR_TS_Location_13_length',
 'Pport_uR_TS_Location_3_plat_@platsup',
 'Pport_uR_TS_Location_3_plat_@cisPlatsup',
 'Pport_uR_TS_Location_0_plat_@cisPlatsup',
 'Pport_uR_TS_Location_1_plat_@cisPlatsup',
 'Pport_uR_TS_Location_4_arr_@wet',
 'Pport_uR_@requestSource',
 'Pport_uR_@requestID',
 'Pport_uR_TS_Location_@wtp',
 'Pport_uR_TS_Location_pass_@et',
 'Pport_uR_TS_Location_pass_@src',
 'Pport_uR_TS_Location_plat_@platsup',
 'Pport_uR_TS_Location_plat_@cisPlatsup',
 'Pport_uR_TS_Location_11_arr_@wet',
 'Pport_uR_TS_Location_11_plat_@platsrc',
 'Pport_uR_TS_Location_11_plat_#text',
 'Pport_uR_TS_Location_12_@wta',
 'Pport_uR_TS_Location_12_@wtd',
 'Pport_uR_TS_Location_12_@pta',
 'Pport_uR_TS_Location_12_@ptd',
 'Pport_uR_TS_Location_12_arr_@et',
 'Pport_uR_TS_Location_12_arr_@wet',
 'Pport_uR_TS_Location_12_arr_@src',
 'Pport_uR_TS_Location_12_dep_@et',
 'Pport_uR_TS_Location_12_dep_@src',
 'Pport_uR_TS_Location_12_plat_@platsrc',
 'Pport_uR_TS_Location_12_plat_#text',
 'Pport_uR_TS_Location_13_@wtp',
 'Pport_uR_TS_Location_13_pass_@et',
 'Pport_uR_TS_Location_13_pass_@src',
 'Pport_uR_TS_Location_14_@tpl',
 'Pport_uR_TS_Location_14_@wta',
 'Pport_uR_TS_Location_14_@wtd',
 'Pport_uR_TS_Location_14_@pta',
 'Pport_uR_TS_Location_14_@ptd',
 'Pport_uR_TS_Location_14_arr_@et',
 'Pport_uR_TS_Location_14_arr_@wet',
 'Pport_uR_TS_Location_14_arr_@src',
 'Pport_uR_TS_Location_14_dep_@et',
 'Pport_uR_TS_Location_14_dep_@src',
 'Pport_uR_TS_Location_14_plat_@platsrc',
 'Pport_uR_TS_Location_14_plat_#text',
 'Pport_uR_TS_Location_14_length',
 'Pport_uR_TS_Location_15_@tpl',
 'Pport_uR_TS_Location_15_@wta',
 'Pport_uR_TS_Location_15_@wtd',
 'Pport_uR_TS_Location_15_@pta',
 'Pport_uR_TS_Location_15_@ptd',
 'Pport_uR_TS_Location_15_arr_@et',
 'Pport_uR_TS_Location_15_arr_@src',
 'Pport_uR_TS_Location_15_dep_@et',
 'Pport_uR_TS_Location_15_dep_@src',
 'Pport_uR_TS_Location_15_plat_@platsrc',
 'Pport_uR_TS_Location_15_plat_#text',
 'Pport_uR_TS_Location_15_length',
 'Pport_uR_TS_Location_16_@tpl',
 'Pport_uR_TS_Location_16_@wta',
 'Pport_uR_TS_Location_16_@wtd',
 'Pport_uR_TS_Location_16_@pta',
 'Pport_uR_TS_Location_16_@ptd',
 'Pport_uR_TS_Location_16_arr_@et',
 'Pport_uR_TS_Location_16_arr_@wet',
 'Pport_uR_TS_Location_16_arr_@src',
 'Pport_uR_TS_Location_16_dep_@et',
 'Pport_uR_TS_Location_16_dep_@src',
 'Pport_uR_TS_Location_16_plat_@platsrc',
 'Pport_uR_TS_Location_16_plat_#text',
 'Pport_uR_TS_Location_16_length',
 'Pport_uR_TS_Location_17_@tpl',
 'Pport_uR_TS_Location_17_@wta',
 'Pport_uR_TS_Location_17_@wtd',
 'Pport_uR_TS_Location_17_@pta',
 'Pport_uR_TS_Location_17_@ptd',
 'Pport_uR_TS_Location_17_arr_@et',
 'Pport_uR_TS_Location_17_arr_@wet',
 'Pport_uR_TS_Location_17_arr_@src',
 'Pport_uR_TS_Location_17_dep_@et',
 'Pport_uR_TS_Location_17_dep_@src',
 'Pport_uR_TS_Location_17_plat_@platsrc',
 'Pport_uR_TS_Location_17_plat_#text',
 'Pport_uR_TS_Location_17_length',
 'Pport_uR_TS_Location_18_@tpl',
 'Pport_uR_TS_Location_18_@wta',
 'Pport_uR_TS_Location_18_@wtd',
 'Pport_uR_TS_Location_18_@pta',
 'Pport_uR_TS_Location_18_@ptd',
 'Pport_uR_TS_Location_18_arr_@et',
 'Pport_uR_TS_Location_18_arr_@src',
 'Pport_uR_TS_Location_18_dep_@et',
 'Pport_uR_TS_Location_18_dep_@src',
 'Pport_uR_TS_Location_18_plat_@platsrc',
 'Pport_uR_TS_Location_18_plat_#text',
 'Pport_uR_TS_Location_18_length',
 'Pport_uR_TS_Location_19_@tpl',
 'Pport_uR_TS_Location_19_@wta',
 'Pport_uR_TS_Location_19_@wtd',
 'Pport_uR_TS_Location_19_@pta',
 'Pport_uR_TS_Location_19_@ptd',
 'Pport_uR_TS_Location_19_arr_@et',
 'Pport_uR_TS_Location_19_arr_@src',
 'Pport_uR_TS_Location_19_dep_@et',
 'Pport_uR_TS_Location_19_dep_@src',
 'Pport_uR_TS_Location_19_plat_@platsrc',
 'Pport_uR_TS_Location_19_plat_#text',
 'Pport_uR_TS_Location_19_length',
 'Pport_uR_TS_Location_20_@tpl',
 'Pport_uR_TS_Location_20_@wta',
 'Pport_uR_TS_Location_20_@pta',
 'Pport_uR_TS_Location_20_arr_@et',
 'Pport_uR_TS_Location_20_arr_@wet',
 'Pport_uR_TS_Location_20_arr_@src',
 'Pport_uR_TS_Location_20_plat',
 'Pport_uR_TS_Location_20_length',
 'Pport_uR_TS_Location_0_dep_@at',
 'Pport_uR_TS_Location_0_dep_@atClass',
 'Pport_uR_TS_Location_0_suppr',
 'Pport_uR_TS_Location_pass_@at',
 'Pport_uR_TS_Location_pass_@atClass',
 'Pport_uR_TS_Location_0_arr_@delayed',
 'Pport_uR_TS_Location_1_pass_@delayed',
 'Pport_uR_TS_Location_5_@wtp',
 'Pport_uR_TS_Location_5_pass_@et',
 'Pport_uR_TS_Location_5_pass_@src',
 'Pport_uR_TS_Location_7_@wtp',
 'Pport_uR_TS_Location_7_pass_@et',
 'Pport_uR_TS_Location_7_pass_@src',
 'Pport_uR_TS_Location_5_plat_@conf',
 'Pport_uR_TS_Location_arr_@delayed',
 'Pport_uR_TS_Location_0_pass_@at',
 'Pport_uR_TS_Location_0_pass_@atClass',
 'Pport_uR_TS_Location_2_plat_@cisPlatsup',
 'Pport_uR_TS_Location_5_plat_@cisPlatsup',
 'Pport_uR_TS_@isReverseFormation',
 'Pport_uR_TS_Location_5_pass_@delayed',
 'Pport_uR_TS_Location_6_plat_@platsup',
 'Pport_uR_TS_Location_6_plat_@cisPlatsup',
 'Pport_uR_TS_Location_7_pass_@delayed',
 'Pport_uR_TS_Location_8_@wtp',
 'Pport_uR_TS_Location_8_pass_@et',
 'Pport_uR_TS_Location_8_pass_@delayed',
 'Pport_uR_TS_Location_8_pass_@src',
 'Pport_uR_TS_Location_8_plat_@platsup',
 'Pport_uR_TS_Location_8_plat_@cisPlatsup',
 'Pport_uR_TS_Location_10_@wtp',
 'Pport_uR_TS_Location_10_pass_@et',
 'Pport_uR_TS_Location_10_pass_@delayed',
 'Pport_uR_TS_Location_10_pass_@src',
 'Pport_uR_TS_Location_11_arr_@delayed',
 'Pport_uR_TS_Location_11_dep_@wet',
 'Pport_uR_TS_Location_11_dep_@delayed',
 'Pport_uR_TS_Location_13_pass_@delayed',
 'Pport_uR_TS_Location_14_@wtp',
 'Pport_uR_TS_Location_14_pass_@et',
 'Pport_uR_TS_Location_14_pass_@delayed',
 'Pport_uR_TS_Location_14_pass_@src',
 'Pport_uR_TS_Location_15_@wtp',
 'Pport_uR_TS_Location_15_pass_@et',
 'Pport_uR_TS_Location_15_pass_@delayed',
 'Pport_uR_TS_Location_15_pass_@src',
 'Pport_uR_TS_Location_16_@wtp',
 'Pport_uR_TS_Location_16_pass_@et',
 'Pport_uR_TS_Location_16_pass_@delayed',
 'Pport_uR_TS_Location_16_pass_@src',
 'Pport_uR_TS_Location_16_plat_@platsup',
 'Pport_uR_TS_Location_16_plat_@cisPlatsup',
 'Pport_uR_TS_Location_17_@wtp',
 'Pport_uR_TS_Location_17_pass_@et',
 'Pport_uR_TS_Location_17_pass_@delayed',
 'Pport_uR_TS_Location_17_pass_@src',
 'Pport_uR_TS_Location_18_@wtp',
 'Pport_uR_TS_Location_18_pass_@et',
 'Pport_uR_TS_Location_18_pass_@delayed',
 'Pport_uR_TS_Location_18_pass_@src',
 'Pport_uR_TS_Location_19_@wtp',
 'Pport_uR_TS_Location_19_pass_@et',
 'Pport_uR_TS_Location_19_pass_@delayed',
 'Pport_uR_TS_Location_19_pass_@src',
 'Pport_uR_TS_Location_20_@wtp',
 'Pport_uR_TS_Location_20_pass_@et',
 'Pport_uR_TS_Location_20_pass_@delayed',
 'Pport_uR_TS_Location_20_pass_@src',
 'Pport_uR_TS_Location_20_plat_@platsup',
 'Pport_uR_TS_Location_20_plat_@cisPlatsup',
 'Pport_uR_TS_Location_20_plat_#text',
 'Pport_uR_TS_Location_21_@tpl',
 'Pport_uR_TS_Location_21_@wtp',
 'Pport_uR_TS_Location_21_pass_@et',
 'Pport_uR_TS_Location_21_pass_@delayed',
 'Pport_uR_TS_Location_21_pass_@src',
 'Pport_uR_TS_Location_22_@tpl',
 'Pport_uR_TS_Location_22_@wtp',
 'Pport_uR_TS_Location_22_pass_@et',
 'Pport_uR_TS_Location_22_pass_@delayed',
 'Pport_uR_TS_Location_22_pass_@src',
 'Pport_uR_TS_Location_23_@tpl',
 'Pport_uR_TS_Location_23_@wtp',
 'Pport_uR_TS_Location_23_pass_@et',
 'Pport_uR_TS_Location_23_pass_@delayed',
 'Pport_uR_TS_Location_23_pass_@src',
 'Pport_uR_TS_Location_24_@tpl',
 'Pport_uR_TS_Location_24_@wtp',
 'Pport_uR_TS_Location_24_pass_@et',
 'Pport_uR_TS_Location_24_pass_@delayed',
 'Pport_uR_TS_Location_24_pass_@src',
 'Pport_uR_TS_Location_25_@tpl',
 'Pport_uR_TS_Location_25_@wtp',
 'Pport_uR_TS_Location_25_pass_@et',
 'Pport_uR_TS_Location_25_pass_@delayed',
 'Pport_uR_TS_Location_25_pass_@src',
 'Pport_uR_TS_Location_26_@tpl',
 'Pport_uR_TS_Location_26_@wtp',
 'Pport_uR_TS_Location_26_pass_@et',
 'Pport_uR_TS_Location_26_pass_@delayed',
 'Pport_uR_TS_Location_26_pass_@src',
 'Pport_uR_TS_Location_27_@tpl',
 'Pport_uR_TS_Location_27_@wtp',
 'Pport_uR_TS_Location_27_pass_@et',
 'Pport_uR_TS_Location_27_pass_@delayed',
 'Pport_uR_TS_Location_27_pass_@src',
 'Pport_uR_TS_Location_28_@tpl',
 'Pport_uR_TS_Location_28_@wtp',
 'Pport_uR_TS_Location_28_pass_@et',
 'Pport_uR_TS_Location_28_pass_@delayed',
 'Pport_uR_TS_Location_28_pass_@src',
 'Pport_uR_TS_Location_29_@tpl',
 'Pport_uR_TS_Location_29_@wtp',
 'Pport_uR_TS_Location_29_pass_@et',
 'Pport_uR_TS_Location_29_pass_@delayed',
 'Pport_uR_TS_Location_29_pass_@src',
 'Pport_uR_TS_Location_30_@tpl',
 'Pport_uR_TS_Location_30_@wtp',
 'Pport_uR_TS_Location_30_pass_@et',
 'Pport_uR_TS_Location_30_pass_@delayed',
 'Pport_uR_TS_Location_30_pass_@src',
 'Pport_uR_TS_Location_30_plat_@platsup',
 'Pport_uR_TS_Location_30_plat_@cisPlatsup',
 'Pport_uR_TS_Location_30_plat_@platsrc',
 'Pport_uR_TS_Location_30_plat_#text',
 'Pport_uR_TS_Location_31_@tpl',
 'Pport_uR_TS_Location_31_@wtp',
 'Pport_uR_TS_Location_31_pass_@et',
 'Pport_uR_TS_Location_31_pass_@delayed',
 'Pport_uR_TS_Location_31_pass_@src',
 'Pport_uR_TS_Location_32_@tpl',
 'Pport_uR_TS_Location_32_@wtp',
 'Pport_uR_TS_Location_32_pass_@et',
 'Pport_uR_TS_Location_32_pass_@delayed',
 'Pport_uR_TS_Location_32_pass_@src',
 'Pport_uR_TS_Location_33_@tpl',
 'Pport_uR_TS_Location_33_@wtp',
 'Pport_uR_TS_Location_33_pass_@et',
 'Pport_uR_TS_Location_33_pass_@delayed',
 'Pport_uR_TS_Location_33_pass_@src',
 'Pport_uR_TS_Location_34_@tpl',
 'Pport_uR_TS_Location_34_@wta',
 'Pport_uR_TS_Location_34_@wtd',
 'Pport_uR_TS_Location_34_@pta',
 'Pport_uR_TS_Location_34_@ptd',
 'Pport_uR_TS_Location_34_arr_@et',
 'Pport_uR_TS_Location_34_arr_@wet',
 'Pport_uR_TS_Location_34_arr_@delayed',
 'Pport_uR_TS_Location_34_arr_@src',
 'Pport_uR_TS_Location_34_dep_@et',
 'Pport_uR_TS_Location_34_dep_@delayed',
 'Pport_uR_TS_Location_34_dep_@src',
 'Pport_uR_TS_Location_34_plat',
 'Pport_uR_TS_Location_35_@tpl',
 'Pport_uR_TS_Location_35_@wtp',
 'Pport_uR_TS_Location_35_pass_@et',

In [4]:
df['Pport_uR_TS_Location_8_plat'].head(10)

0    1.0
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: Pport_uR_TS_Location_8_plat, dtype: float64

In [5]:
df.shape

(2503, 2324)

In [14]:
df['Pport_uR_TS_@ssd'].head(10)

0    2025-07-22
1    2025-07-22
2    2025-07-22
3    2025-07-22
4    2025-07-22
5    2025-07-22
6    2025-07-22
7    2025-07-22
8    2025-07-22
9    2025-07-22
Name: Pport_uR_TS_@ssd, dtype: object

In [17]:
import pandas as pd
import s3fs

s3_path = "s3://darwin-raildata-mlops/transformed-data/preprocessed-features-data/"
long_df = pd.read_parquet(s3_path, storage_options={"anon": False})

print(long_df.shape)

FileNotFoundError: darwin-raildata-mlops/transformed-data/preprocessed-features-data/380c53e999b64d37b9af83291a259425.snappy.parquet

In [47]:
import pandas as pd
import s3fs
new_df = pd.read_csv("s3://darwin-raildata-mlops/darwin-long-format-data/events_long.csv")

C:\Users\personal\AppData\Local\Temp\ipykernel_6232\45822042.py:3: DtypeWarning: Columns (78,79,82,84,85,86,88,89,90,92,93,94,95,96,97,98,99,100,102,103) have mixed types. Specify dtype option on import or set low_memory=False.
  new_df = pd.read_csv("s3://darwin-raildata-mlops/darwin-long-format-data/events_long.csv")

In [48]:
print(new_df.columns.tolist())
print(new_df.head())

['Pport_@xmlns', 'Pport_ns2', 'Pport_ns3', 'Pport_ns4', 'Pport_ns5', 'Pport_ns6', 'Pport_ns7', 'Pport_ns8', 'Pport_ns9', 'Pport_ns10', 'Pport_ns11', 'Pport_ns12', 'Pport_@ts', 'Pport_@version', 'Pport_uR_@updateOrigin', 'Pport_uR_@requestSource', 'Pport_uR_@requestID', 'Pport_uR_TS_@rid', 'Pport_uR_TS_@uid', 'Pport_uR_TS_@ssd', 'Pport_uR_TS_Location_@tpl', 'Pport_uR_TS_Location_@wta', 'Pport_uR_TS_Location_@wtd', 'Pport_uR_TS_Location_@pta', 'Pport_uR_TS_Location_@ptd', 'Pport_uR_TS_Location_arr_@et', 'Pport_uR_TS_Location_arr_@wet', 'Pport_uR_TS_Location_arr_@src', 'Pport_uR_TS_Location_dep_@et', 'Pport_uR_TS_Location_dep_@src', 'Pport_uR_TS_Location_plat_@platsrc', 'Pport_uR_TS_Location_plat_#text', 'Pport_uR_TS_Location_length', 'Pport_uR_TS_Location_plat', 'Pport_uR_TS_Location_@wtp', 'Pport_uR_TS_Location_pass_@at', 'Pport_uR_TS_Location_pass_@atClass', 'Pport_uR_TS_Location_pass_@src', 'Pport_uR_formationLoading_@fid', 'Pport_uR_formationLoading_@rid', 'Pport_uR_formationLoading_@tpl', 'Pport_uR_formationLoading_@wta', 'Pport_uR_formationLoading_@wtd', 'Pport_uR_formationLoading_@pta', 'Pport_uR_formationLoading_@ptd', 'Pport_uR_formationLoading_loading_0_@coachNumber', 'Pport_uR_formationLoading_loading_0_#text', 'Pport_uR_formationLoading_loading_1_@coachNumber', 'Pport_uR_formationLoading_loading_1_#text', 'Pport_uR_formationLoading_loading_2_@coachNumber', 'Pport_uR_formationLoading_loading_2_#text', 'Pport_uR_formationLoading_loading_3_@coachNumber', 'Pport_uR_formationLoading_loading_3_#text', 'Pport_uR_formationLoading_loading_4_@coachNumber', 'Pport_uR_formationLoading_loading_4_#text', 'Pport_uR_formationLoading_loading_5_@coachNumber', 'Pport_uR_formationLoading_loading_5_#text', 'Pport_uR_formationLoading_loading_6_@coachNumber', 'Pport_uR_formationLoading_loading_6_#text', 'Pport_uR_formationLoading_loading_7_@coachNumber', 'Pport_uR_formationLoading_loading_7_#text', 'Pport_uR_formationLoading_loading_8_@coachNumber', 'Pport_uR_formationLoading_loading_8_#text', 'Pport_uR_TS_Location_arr_@at', 'Pport_uR_TS_Location_arr_@atClass', 'Pport_uR_TS_Location_dep_@at', 'Pport_uR_TS_Location_dep_@atClass', 'Pport_uR_TS_Location_pass_@et', 'Pport_uR_TS_Location_plat_@platsup', 'Pport_uR_TS_Location_plat_@cisPlatsup', 'Pport_uR_TS_Location_plat_@conf', '@tpl', '@wtp', 'pass_@et', 'pass_@src', 'length', 'plat_@platsup', 'plat_@cisPlatsup', 'plat_@platsrc', 'plat_@conf', 'plat_#text', '@wta', '@wtd', '@pta', '@ptd', 'arr_@at', 'arr_@atClass', 'arr_@src', 'dep_@at', 'dep_@atClass', 'dep_@src', 'arr_@et', 'dep_@et', 'plat', 'pass_@at', 'pass_@atClass', 'pass_@srcInst', 'arr_@srcInst', 'dep_@srcInst', 'arr_@wet', 'dep_@etmin', 'location_index', 'arr_@etmin', 'dep_@wet']
                                   Pport_@xmlns  \
0  http://www.thalesgroup.com/rtti/PushPort/v16
1  http://www.thalesgroup.com/rtti/PushPort/v16
2  http://www.thalesgroup.com/rtti/PushPort/v16
3  http://www.thalesgroup.com/rtti/PushPort/v16
4  http://www.thalesgroup.com/rtti/PushPort/v16

                                           Pport_ns2  \
0  http://www.thalesgroup.com/rtti/PushPort/Sched...
1  http://www.thalesgroup.com/rtti/PushPort/Sched...
2  http://www.thalesgroup.com/rtti/PushPort/Sched...
3  http://www.thalesgroup.com/rtti/PushPort/Sched...
4  http://www.thalesgroup.com/rtti/PushPort/Sched...

                                           Pport_ns3  \
0  http://www.thalesgroup.com/rtti/PushPort/Sched...
1  http://www.thalesgroup.com/rtti/PushPort/Sched...
2  http://www.thalesgroup.com/rtti/PushPort/Sched...
3  http://www.thalesgroup.com/rtti/PushPort/Sched...
4  http://www.thalesgroup.com/rtti/PushPort/Sched...

                                           Pport_ns4  \
0  http://www.thalesgroup.com/rtti/PushPort/Forma...
1  http://www.thalesgroup.com/rtti/PushPort/Forma...
2  http://www.thalesgroup.com/rtti/PushPort/Forma...
3  http://www.thalesgroup.com/rtti/PushPort/Forma...
4  http://www.thalesgroup.com/rtti/PushPort/Forma...

                                           Pport_ns5  \
0  http://www.thalesgroup.com/rtti/PushPort/Forec...
1  http://www.thalesgroup.com/rtti/PushPort/Forec...
2  http://www.thalesgroup.com/rtti/PushPort/Forec...
3  http://www.thalesgroup.com/rtti/PushPort/Forec...
4  http://www.thalesgroup.com/rtti/PushPort/Forec...

                                           Pport_ns6  \
0  http://www.thalesgroup.com/rtti/PushPort/Forma...
1  http://www.thalesgroup.com/rtti/PushPort/Forma...
2  http://www.thalesgroup.com/rtti/PushPort/Forma...
3  http://www.thalesgroup.com/rtti/PushPort/Forma...
4  http://www.thalesgroup.com/rtti/PushPort/Forma...

                                           Pport_ns7  \
0  http://www.thalesgroup.com/rtti/PushPort/Stati...
1  http://www.thalesgroup.com/rtti/PushPort/Stati...
2  http://www.thalesgroup.com/rtti/PushPort/Stati...
3  http://www.thalesgroup.com/rtti/PushPort/Stati...
4  http://www.thalesgroup.com/rtti/PushPort/Stati...

                                           Pport_ns8  \
0  http://www.thalesgroup.com/rtti/PushPort/Train...
1  http://www.thalesgroup.com/rtti/PushPort/Train...
2  http://www.thalesgroup.com/rtti/PushPort/Train...
3  http://www.thalesgroup.com/rtti/PushPort/Train...
4  http://www.thalesgroup.com/rtti/PushPort/Train...

                                           Pport_ns9  \
0  http://www.thalesgroup.com/rtti/PushPort/Train...
1  http://www.thalesgroup.com/rtti/PushPort/Train...
2  http://www.thalesgroup.com/rtti/PushPort/Train...
3  http://www.thalesgroup.com/rtti/PushPort/Train...
4  http://www.thalesgroup.com/rtti/PushPort/Train...

                                          Pport_ns10  ... pass_@at  \
0  http://www.thalesgroup.com/rtti/PushPort/TDDat...  ...      NaN
1  http://www.thalesgroup.com/rtti/PushPort/TDDat...  ...      NaN
2  http://www.thalesgroup.com/rtti/PushPort/TDDat...  ...      NaN
3  http://www.thalesgroup.com/rtti/PushPort/TDDat...  ...      NaN
4  http://www.thalesgroup.com/rtti/PushPort/TDDat...  ...      NaN

  pass_@atClass pass_@srcInst  arr_@srcInst dep_@srcInst arr_@wet dep_@etmin  \
0           NaN           NaN           NaN          NaN      NaN        NaN
1           NaN           NaN           NaN          NaN      NaN        NaN
2           NaN           NaN           NaN          NaN      NaN        NaN
3           NaN           NaN           NaN          NaN      NaN        NaN
4           NaN           NaN           NaN          NaN      NaN        NaN

   location_index arr_@etmin dep_@wet
0               0        NaN      NaN
1               0        NaN      NaN
2               0        NaN      NaN
3               0        NaN      NaN
4               0        NaN      NaN

[5 rows x 104 columns]

In [49]:
new_df.shape

(10416, 104)

In [28]:
new_df.tail(10)

,Pport_@xmlns,Pport_ns2,Pport_ns3,Pport_ns4,Pport_ns5,Pport_ns6,Pport_ns7,Pport_ns8,Pport_ns9,Pport_ns10,...,Pport_uR_TS_Location_17_@wta,Pport_uR_TS_Location_17_@wtd,Pport_uR_TS_Location_17_@pta,Pport_uR_TS_Location_17_@ptd,Pport_uR_TS_Location_17_arr_@et,Pport_uR_TS_Location_17_arr_@wet,Pport_uR_TS_Location_17_arr_@src,Pport_uR_TS_Location_17_dep_@et,Pport_uR_TS_Location_17_dep_@src,Pport_uR_TS_Location_17_plat
0,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,11:53,11:55,11:53,11:55,11:53,11:52,Darwin,11:55,Darwin,9.0

In [24]:
!pip install awswrangler

Collecting awswrangler
  Using cached awswrangler-3.12.1-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: boto3<2,>=1.20.32 in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from awswrangler) (1.39.8)
Requirement already satisfied: botocore<2,>=1.23.32 in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from awswrangler) (1.39.8)
Requirement already satisfied: numpy<3.0,>=1.26 in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from awswrangler) (2.0.2)
Requirement already satisfied: packaging<26.0,>=21.1 in c:\users\personal\appdata\roaming\python\python313\site-packages (from awswrangler) (24.2)
Requirement already satisfied: pandas<3.0.0,>=1.2.0 in c:\users\personal\appdata\roaming\python\python313\site-packages (from awswrangler) (2.2.3)
Requirement already satisfied: pyarrow<21.0.0,>=18.0.0 in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from awswrangler) (20.0.0)
Requirement already satisfied: setuptools in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from awswrangler) (75.6.0)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from awswrangler) (4.14.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from boto3<2,>=1.20.32->awswrangler) (1.0.1)
Requirement already satisfied: s3transfer<0.14.0,>=0.13.0 in c:\users\personal\appdata\local\programs\python\python313\lib\site-packages (from boto3<2,>=1.20.32->awswrangler) (0.13.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\personal\appdata\roaming\python\python313\site-packages (from botocore<2,>=1.23.32->awswrangler) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\personal\appdata\roaming\python\python313\site-packages (from botocore<2,>=1.23.32->awswrangler) (2.2.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\personal\appdata\roaming\python\python313\site-packages (from pandas<3.0.0,>=1.2.0->awswrangler) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\personal\appdata\roaming\python\python313\site-packages (from pandas<3.0.0,>=1.2.0->awswrangler) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\personal\appdata\roaming\python\python313\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2,>=1.23.32->awswrangler) (1.17.0)
Downloading awswrangler-3.12.1-py3-none-any.whl (379 kB)
Installing collected packages: awswrangler
Successfully installed awswrangler-3.12.1

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: C:\Users\personal\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [23]:
import boto3
import pandas as pd

s3 = boto3.client("s3")
bucket = "darwin-raildata-mlops"
prefix = "transformed-data/preprocessed-features-data/"

# List objects
response = s3.list_objects_v2(Bucket=bucket, Prefix=prefix)
files = [obj["Key"] for obj in response.get("Contents", []) if obj["Key"].endswith(".parquet")]

# Read first file
first_file = files[0]
s3_path = f"s3://{bucket}/{first_file}"
df = pd.read_parquet(s3_path, storage_options={"anon": False})
print(df.shape)

FileNotFoundError: darwin-raildata-mlops/transformed-data/preprocessed-features-data/380c53e999b64d37b9af83291a259425.snappy.parquet

In [46]:
import awswrangler as wr

s3_path = "s3://darwin-raildata-mlops/darwin-long-format-data/events_long.csv"

long_df = wr.s3.read_parquet(path=s3_path)
print(long_df.shape)

KeyboardInterrupt:

In [13]:
print(df.shape)

(2505, 2324)

In [45]:
new_df.head(20)

,Pport_@xmlns,Pport_ns2,Pport_ns3,Pport_ns4,Pport_ns5,Pport_ns6,Pport_ns7,Pport_ns8,Pport_ns9,Pport_ns10,...,plat_@platsup,plat_@cisPlatsup,plat_#text,plat_@platsrc,plat_@conf,service_date,scheduled_arrival_dt,actual_arrival_dt,arrival_delay_minutes,day_of_week
0,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
1,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
2,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
3,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
4,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
5,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
6,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
7,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
8,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
9,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
10,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
11,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
12,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
13,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
14,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
15,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
16,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
17,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
18,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0
19,http://www.thalesgroup.com/rtti/PushPort/v16,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Sched...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Forec...,http://www.thalesgroup.com/rtti/PushPort/Forma...,http://www.thalesgroup.com/rtti/PushPort/Stati...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/Train...,http://www.thalesgroup.com/rtti/PushPort/TDDat...,...,NaN,NaN,NaN,NaN,NaN,2025-08-18,2025-08-18,2025-08-18,0.0,0

In [50]:
new_df['Pport_uR_TS_Location_@wtd'].head(10)

0    13:58:30
1       17:58
2    13:58:30
3       13:58
4       13:58
5       17:59
6    13:08:30
7         NaN
8         NaN
9         NaN
Name: Pport_uR_TS_Location_@wtd, dtype: object

In [51]:
new_df['Pport_uR_TS_Location_arr_@at'].tail(10)

10406      NaN
10407    11:57
10408      NaN
10409      NaN
10410      NaN
10411      NaN
10412      NaN
10413      NaN
10414      NaN
10415      NaN
Name: Pport_uR_TS_Location_arr_@at, dtype: object

In [52]:
new_df['Pport_uR_TS_@uid'].head(10)

0    G55881
1    G56357
2    Y68403
3    Y67893
4    Y70868
5    Y68172
6    L52105
7    P19683
8       NaN
9       NaN
Name: Pport_uR_TS_@uid, dtype: object

In [53]:
new_df['Pport_uR_TS_@ssd'].head(10)

0    2025-08-18
1    2025-08-18
2    2025-08-18
3    2025-08-18
4    2025-08-18
5    2025-08-18
6    2025-08-18
7    2025-08-18
8           NaN
9           NaN
Name: Pport_uR_TS_@ssd, dtype: object

In [12]:
long_df.columns.unique().tolist()

['Pport_@xmlns',
 'Pport_ns2',
 'Pport_ns3',
 'Pport_ns4',
 'Pport_ns5',
 'Pport_ns6',
 'Pport_ns7',
 'Pport_ns8',
 'Pport_ns9',
 'Pport_ns10',
 'Pport_ns11',
 'Pport_ns12',
 'Pport_@ts',
 'Pport_@version',
 'Pport_uR_@updateOrigin',
 'Pport_uR_TS_@rid',
 'Pport_uR_TS_@uid',
 'Pport_uR_TS_@ssd',
 'Pport_uR_TS_Location_0_@tpl',
 'Pport_uR_TS_Location_0_@wtp',
 'Pport_uR_TS_Location_0_pass_@et',
 'Pport_uR_TS_Location_0_pass_@delayed',
 'Pport_uR_TS_Location_0_pass_@src',
 'Pport_uR_TS_Location_0_length',
 'Pport_uR_TS_Location_1_@tpl',
 'Pport_uR_TS_Location_1_@wta',
 'Pport_uR_TS_Location_1_@wtd',
 'Pport_uR_TS_Location_1_@pta',
 'Pport_uR_TS_Location_1_@ptd',
 'Pport_uR_TS_Location_1_arr_@et',
 'Pport_uR_TS_Location_1_arr_@delayed',
 'Pport_uR_TS_Location_1_arr_@src',
 'Pport_uR_TS_Location_1_dep_@et',
 'Pport_uR_TS_Location_1_dep_@delayed',
 'Pport_uR_TS_Location_1_dep_@src',
 'Pport_uR_TS_Location_1_length',
 'Pport_uR_TS_Location_2_@tpl',
 'Pport_uR_TS_Location_2_@wtp',
 'Pport_uR_TS_Location_2_pass_@et',
 'Pport_uR_TS_Location_2_pass_@delayed',
 'Pport_uR_TS_Location_2_pass_@src',
 'Pport_uR_TS_Location_2_length',
 'Pport_uR_TS_Location_3_@tpl',
 'Pport_uR_TS_Location_3_@wta',
 'Pport_uR_TS_Location_3_@wtd',
 'Pport_uR_TS_Location_3_@pta',
 'Pport_uR_TS_Location_3_@ptd',
 'Pport_uR_TS_Location_3_arr_@et',
 'Pport_uR_TS_Location_3_arr_@delayed',
 'Pport_uR_TS_Location_3_arr_@src',
 'Pport_uR_TS_Location_3_dep_@et',
 'Pport_uR_TS_Location_3_dep_@delayed',
 'Pport_uR_TS_Location_3_dep_@src',
 'Pport_uR_TS_Location_3_length',
 'Pport_uR_TS_Location_4_@tpl',
 'Pport_uR_TS_Location_4_@wtp',
 'Pport_uR_TS_Location_4_pass_@et',
 'Pport_uR_TS_Location_4_pass_@delayed',
 'Pport_uR_TS_Location_4_pass_@src',
 'Pport_uR_TS_Location_4_length',
 'Pport_uR_TS_Location_5_@tpl',
 'Pport_uR_TS_Location_5_@wta',
 'Pport_uR_TS_Location_5_@wtd',
 'Pport_uR_TS_Location_5_@pta',
 'Pport_uR_TS_Location_5_@ptd',
 'Pport_uR_TS_Location_5_arr_@et',
 'Pport_uR_TS_Location_5_arr_@delayed',
 'Pport_uR_TS_Location_5_arr_@src',
 'Pport_uR_TS_Location_5_dep_@et',
 'Pport_uR_TS_Location_5_dep_@delayed',
 'Pport_uR_TS_Location_5_dep_@src',
 'Pport_uR_TS_Location_5_length',
 'Pport_uR_TS_Location_6_@tpl',
 'Pport_uR_TS_Location_6_@wtp',
 'Pport_uR_TS_Location_6_pass_@et',
 'Pport_uR_TS_Location_6_pass_@delayed',
 'Pport_uR_TS_Location_6_pass_@src',
 'Pport_uR_TS_Location_6_length',
 'Pport_uR_TS_Location_7_@tpl',
 'Pport_uR_TS_Location_7_@wta',
 'Pport_uR_TS_Location_7_@wtd',
 'Pport_uR_TS_Location_7_@pta',
 'Pport_uR_TS_Location_7_@ptd',
 'Pport_uR_TS_Location_7_arr_@et',
 'Pport_uR_TS_Location_7_arr_@delayed',
 'Pport_uR_TS_Location_7_arr_@src',
 'Pport_uR_TS_Location_7_dep_@et',
 'Pport_uR_TS_Location_7_dep_@delayed',
 'Pport_uR_TS_Location_7_dep_@src',
 'Pport_uR_TS_Location_7_length',
 'Pport_uR_TS_Location_8_@tpl',
 'Pport_uR_TS_Location_8_@wta',
 'Pport_uR_TS_Location_8_@pta',
 'Pport_uR_TS_Location_8_arr_@et',
 'Pport_uR_TS_Location_8_arr_@wet',
 'Pport_uR_TS_Location_8_arr_@delayed',
 'Pport_uR_TS_Location_8_arr_@src',
 'Pport_uR_TS_Location_8_length',
 'Pport_uR_TS_Location_@tpl',
 'Pport_uR_TS_Location_@wta',
 'Pport_uR_TS_Location_@wtd',
 'Pport_uR_TS_Location_@pta',
 'Pport_uR_TS_Location_@ptd',
 'Pport_uR_TS_Location_arr_@at',
 'Pport_uR_TS_Location_arr_@atClass',
 'Pport_uR_TS_Location_arr_@src',
 'Pport_uR_TS_Location_dep_@et',
 'Pport_uR_TS_Location_dep_@src',
 'Pport_uR_TS_Location_plat_@platsrc',
 'Pport_uR_TS_Location_plat_@conf',
 'Pport_uR_TS_Location_plat_#text',
 'Pport_uR_TS_Location_length',
 'Pport_uR_TS_Location_0_@wta',
 'Pport_uR_TS_Location_0_@wtd',
 'Pport_uR_TS_Location_0_@pta',
 'Pport_uR_TS_Location_0_@ptd',
 'Pport_uR_TS_Location_0_arr_@et',
 'Pport_uR_TS_Location_0_arr_@src',
 'Pport_uR_TS_Location_0_dep_@et',
 'Pport_uR_TS_Location_0_dep_@src',
 'Pport_uR_TS_Location_1_@wtp',
 'Pport_uR_TS_Location_1_pass_@et',
 'Pport_uR_TS_Location_1_pass_@src',
 'Pport_uR_TS_Location_2_@wta',
 'Pport_uR_TS_Location_2_@wtd',
 'Pport_uR_TS_Location_2_@pta',
 'Pport_uR_TS_Location_2_@ptd',
 'Pport_uR_TS_Location_2_arr_@et',
 'Pport_uR_TS_Location_2_arr_@src',
 'Pport_uR_TS_Location_2_dep_@et',
 'Pport_uR_TS_Location_2_dep_@src',
 'Pport_uR_TS_Location_3_@wtp',
 'Pport_uR_TS_Location_3_pass_@et',
 'Pport_uR_TS_Location_3_pass_@src',
 'Pport_uR_TS_Location_4_@wta',
 'Pport_uR_TS_Location_4_@wtd',
 'Pport_uR_TS_Location_4_@pta',
 'Pport_uR_TS_Location_4_@ptd',
 'Pport_uR_TS_Location_4_arr_@et',
 'Pport_uR_TS_Location_4_arr_@src',
 'Pport_uR_TS_Location_4_dep_@et',
 'Pport_uR_TS_Location_4_dep_@src',
 'Pport_uR_TS_Location_4_plat_@platsrc',
 'Pport_uR_TS_Location_4_plat_#text',
 'Pport_uR_TS_Location_5_plat_@platsrc',
 'Pport_uR_TS_Location_5_plat_#text',
 'Pport_uR_TS_Location_6_@wta',
 'Pport_uR_TS_Location_6_@wtd',
 'Pport_uR_TS_Location_6_@pta',
 'Pport_uR_TS_Location_6_@ptd',
 'Pport_uR_TS_Location_6_arr_@et',
 'Pport_uR_TS_Location_6_arr_@src',
 'Pport_uR_TS_Location_6_dep_@et',
 'Pport_uR_TS_Location_6_dep_@src',
 'Pport_uR_TS_Location_6_plat_@platsrc',
 'Pport_uR_TS_Location_6_plat_#text',
 'Pport_uR_TS_Location_7_arr_@wet',
 'Pport_uR_TS_Location_arr_@srcInst',
 'Pport_uR_TS_Location_0_plat_@platsrc',
 'Pport_uR_TS_Location_0_plat_#text',
 'Pport_uR_TS_Location_7_dep_@wet',
 'Pport_uR_TS_Location_8_@wtd',
 'Pport_uR_TS_Location_8_@ptd',
 'Pport_uR_TS_Location_8_dep_@et',
 'Pport_uR_TS_Location_8_dep_@wet',
 'Pport_uR_TS_Location_8_dep_@src',
 'Pport_uR_TS_Location_8_plat_@platsrc',
 'Pport_uR_TS_Location_8_plat_#text',
 'Pport_uR_TS_Location_9_@tpl',
 'Pport_uR_TS_Location_9_@wta',
 'Pport_uR_TS_Location_9_@wtd',
 'Pport_uR_TS_Location_9_@pta',
 'Pport_uR_TS_Location_9_@ptd',
 'Pport_uR_TS_Location_9_arr_@et',
 'Pport_uR_TS_Location_9_arr_@wet',
 'Pport_uR_TS_Location_9_arr_@src',
 'Pport_uR_TS_Location_9_dep_@et',
 'Pport_uR_TS_Location_9_dep_@wet',
 'Pport_uR_TS_Location_9_dep_@src',
 'Pport_uR_TS_Location_9_plat_@platsrc',
 'Pport_uR_TS_Location_9_plat_#text',
 'Pport_uR_TS_Location_9_length',
 'Pport_uR_TS_Location_10_@tpl',
 'Pport_uR_TS_Location_10_@wta',
 'Pport_uR_TS_Location_10_@wtd',
 'Pport_uR_TS_Location_10_@pta',
 'Pport_uR_TS_Location_10_@ptd',
 'Pport_uR_TS_Location_10_arr_@et',
 'Pport_uR_TS_Location_10_arr_@src',
 'Pport_uR_TS_Location_10_dep_@et',
 'Pport_uR_TS_Location_10_dep_@wet',
 'Pport_uR_TS_Location_10_dep_@src',
 'Pport_uR_TS_Location_10_length',
 'Pport_uR_TS_Location_11_@tpl',
 'Pport_uR_TS_Location_11_@wta',
 'Pport_uR_TS_Location_11_@wtd',
 'Pport_uR_TS_Location_11_@pta',
 'Pport_uR_TS_Location_11_@ptd',
 'Pport_uR_TS_Location_11_arr_@et',
 'Pport_uR_TS_Location_11_arr_@src',
 'Pport_uR_TS_Location_11_dep_@et',
 'Pport_uR_TS_Location_11_dep_@src',
 'Pport_uR_TS_Location_11_length',
 'Pport_uR_TS_Location_1_plat_@platsup',
 'Pport_uR_TS_Location_1_plat_#text',
 'Pport_uR_TS_Location_2_arr_@delayed',
 'Pport_uR_TS_Location_2_dep_@delayed',
 'Pport_uR_TS_LateReason',
 'Pport_uR_TS_Location_0_arr_@at',
 'Pport_uR_TS_Location_0_arr_@atClass',
 'Pport_uR_TS_Location_0_arr_@srcInst',
 'Pport_uR_TS_Location_0_plat_@conf',
 'Pport_uR_TS_Location_3_arr_@wet',
 'Pport_uR_TS_Location_3_dep_@wet',
 'Pport_uR_TS_Location_4_plat_@platsup',
 'Pport_uR_TS_Location_4_plat_@cisPlatsup',
 'Pport_uR_TS_Location_5_arr_@wet',
 'Pport_uR_TS_Location_5_dep_@wet',
 'Pport_uR_TS_Location_6_arr_@wet',
 'Pport_uR_TS_Location_1_suppr',
 'Pport_uR_TS_Location_0_dep_@delayed',
 'Pport_uR_TS_Location_3_pass_@delayed',
 'Pport_uR_TS_Location_5_plat_@platsup',
 'Pport_uR_TS_Location_arr_@et',
 'Pport_uR_TS_Location_1_plat_@platsrc',
 'Pport_uR_TS_Location_1_plat_@conf',
 'Pport_uR_TS_Location_0_plat_@platsup',
 'Pport_uR_TS_Location_2_plat_@platsup',
 'Pport_uR_TS_Location_2_plat_#text',
 'Pport_uR_TS_Location_4_plat_@conf',
 'Pport_uR_TS_Location_2_plat_@platsrc',
 'Pport_uR_TS_Location_10_plat_@platsup',
 'Pport_uR_TS_Location_10_plat_@cisPlatsup',
 'Pport_uR_TS_Location_10_plat_@platsrc',
 'Pport_uR_TS_Location_10_plat_#text',
 'Pport_uR_TS_Location_0_pass_@etmin',
 'Pport_uR_TS_Location_1_dep_@etmin',
 'Pport_uR_TS_Location_2_dep_@etmin',
 'Pport_uR_TS_Location_3_dep_@etmin',
 'Pport_uR_TS_Location_3_plat_@platsrc',
 'Pport_uR_TS_Location_3_plat_#text',
 'Pport_uR_TS_Location_4_arr_@delayed',
 'Pport_uR_TS_Location_4_dep_@etmin',
 'Pport_uR_TS_Location_4_dep_@delayed',
 'Pport_uR_TS_Location_5_dep_@etmin',
 'Pport_uR_TS_Location_6_arr_@delayed',
 'Pport_uR_TS_Location_6_dep_@etmin',
 'Pport_uR_TS_Location_6_dep_@delayed',
 'Pport_uR_TS_Location_7_dep_@etmin',
 'Pport_uR_TS_Location_7_plat_@platsrc',
 'Pport_uR_TS_Location_7_plat_#text',
 'Pport_uR_TS_Location_8_dep_@etmin',
 'Pport_uR_TS_Location_8_dep_@delayed',
 'Pport_uR_TS_Location_9_@wtp',
 'Pport_uR_TS_Location_9_pass_@et',
 'Pport_uR_TS_Location_9_pass_@etmin',
 'Pport_uR_TS_Location_9_pass_@delayed',
 'Pport_uR_TS_Location_9_pass_@src',
 'Pport_uR_TS_Location_10_arr_@delayed',
 'Pport_uR_TS_Location_10_dep_@etmin',
 'Pport_uR_TS_Location_10_dep_@delayed',
 'Pport_uR_TS_Location_11_@wtp',
 'Pport_uR_TS_Location_11_pass_@et',
 'Pport_uR_TS_Location_11_pass_@etmin',
 'Pport_uR_TS_Location_11_pass_@delayed',
 'Pport_uR_TS_Location_11_pass_@src',
 'Pport_uR_TS_Location_12_@tpl',
 'Pport_uR_TS_Location_12_@wtp',
 'Pport_uR_TS_Location_12_pass_@et',
 'Pport_uR_TS_Location_12_pass_@etmin',
 'Pport_uR_TS_Location_12_pass_@delayed',
 'Pport_uR_TS_Location_12_pass_@src',
 'Pport_uR_TS_Location_12_length',
 'Pport_uR_TS_Location_13_@tpl',
 'Pport_uR_TS_Location_13_@wta',
 'Pport_uR_TS_Location_13_@pta',
 'Pport_uR_TS_Location_13_arr_@et',
 'Pport_uR_TS_Location_13_arr_@etmin',
 'Pport_uR_TS_Location_13_arr_@delayed',
 'Pport_uR_TS_Location_13_arr_@src',
 'Pport_uR_TS_Location_13_length',
 'Pport_uR_TS_Location_3_plat_@platsup',
 'Pport_uR_TS_Location_3_plat_@cisPlatsup',
 'Pport_uR_TS_Location_0_plat_@cisPlatsup',
 'Pport_uR_TS_Location_1_plat_@cisPlatsup',
 'Pport_uR_TS_Location_4_arr_@wet',
 'Pport_uR_@requestSource',
 'Pport_uR_@requestID',
 'Pport_uR_TS_Location_@wtp',
 'Pport_uR_TS_Location_pass_@et',
 'Pport_uR_TS_Location_pass_@src',
 'Pport_uR_TS_Location_plat_@platsup',
 'Pport_uR_TS_Location_plat_@cisPlatsup',
 'Pport_uR_TS_Location_11_arr_@wet',
 'Pport_uR_TS_Location_11_plat_@platsrc',
 'Pport_uR_TS_Location_11_plat_#text',
 'Pport_uR_TS_Location_12_@wta',
 'Pport_uR_TS_Location_12_@wtd',
 'Pport_uR_TS_Location_12_@pta',
 'Pport_uR_TS_Location_12_@ptd',
 'Pport_uR_TS_Location_12_arr_@et',
 'Pport_uR_TS_Location_12_arr_@wet',
 'Pport_uR_TS_Location_12_arr_@src',
 'Pport_uR_TS_Location_12_dep_@et',
 'Pport_uR_TS_Location_12_dep_@src',
 'Pport_uR_TS_Location_12_plat_@platsrc',
 'Pport_uR_TS_Location_12_plat_#text',
 'Pport_uR_TS_Location_13_@wtp',
 'Pport_uR_TS_Location_13_pass_@et',
 'Pport_uR_TS_Location_13_pass_@src',
 'Pport_uR_TS_Location_14_@tpl',
 'Pport_uR_TS_Location_14_@wta',
 'Pport_uR_TS_Location_14_@wtd',
 'Pport_uR_TS_Location_14_@pta',
 'Pport_uR_TS_Location_14_@ptd',
 'Pport_uR_TS_Location_14_arr_@et',
 'Pport_uR_TS_Location_14_arr_@wet',
 'Pport_uR_TS_Location_14_arr_@src',
 'Pport_uR_TS_Location_14_dep_@et',
 'Pport_uR_TS_Location_14_dep_@src',
 'Pport_uR_TS_Location_14_plat_@platsrc',
 'Pport_uR_TS_Location_14_plat_#text',
 'Pport_uR_TS_Location_14_length',
 'Pport_uR_TS_Location_15_@tpl',
 'Pport_uR_TS_Location_15_@wta',
 'Pport_uR_TS_Location_15_@wtd',
 'Pport_uR_TS_Location_15_@pta',
 'Pport_uR_TS_Location_15_@ptd',
 'Pport_uR_TS_Location_15_arr_@et',
 'Pport_uR_TS_Location_15_arr_@src',
 'Pport_uR_TS_Location_15_dep_@et',
 'Pport_uR_TS_Location_15_dep_@src',
 'Pport_uR_TS_Location_15_plat_@platsrc',
 'Pport_uR_TS_Location_15_plat_#text',
 'Pport_uR_TS_Location_15_length',
 'Pport_uR_TS_Location_16_@tpl',
 'Pport_uR_TS_Location_16_@wta',
 'Pport_uR_TS_Location_16_@wtd',
 'Pport_uR_TS_Location_16_@pta',
 'Pport_uR_TS_Location_16_@ptd',
 'Pport_uR_TS_Location_16_arr_@et',
 'Pport_uR_TS_Location_16_arr_@wet',
 'Pport_uR_TS_Location_16_arr_@src',
 'Pport_uR_TS_Location_16_dep_@et',
 'Pport_uR_TS_Location_16_dep_@src',
 'Pport_uR_TS_Location_16_plat_@platsrc',
 'Pport_uR_TS_Location_16_plat_#text',
 'Pport_uR_TS_Location_16_length',
 'Pport_uR_TS_Location_17_@tpl',
 'Pport_uR_TS_Location_17_@wta',
 'Pport_uR_TS_Location_17_@wtd',
 'Pport_uR_TS_Location_17_@pta',
 'Pport_uR_TS_Location_17_@ptd',
 'Pport_uR_TS_Location_17_arr_@et',
 'Pport_uR_TS_Location_17_arr_@wet',
 'Pport_uR_TS_Location_17_arr_@src',
 'Pport_uR_TS_Location_17_dep_@et',
 'Pport_uR_TS_Location_17_dep_@src',
 'Pport_uR_TS_Location_17_plat_@platsrc',
 'Pport_uR_TS_Location_17_plat_#text',
 'Pport_uR_TS_Location_17_length',
 'Pport_uR_TS_Location_18_@tpl',
 'Pport_uR_TS_Location_18_@wta',
 'Pport_uR_TS_Location_18_@wtd',
 'Pport_uR_TS_Location_18_@pta',
 'Pport_uR_TS_Location_18_@ptd',
 'Pport_uR_TS_Location_18_arr_@et',
 'Pport_uR_TS_Location_18_arr_@src',
 'Pport_uR_TS_Location_18_dep_@et',
 'Pport_uR_TS_Location_18_dep_@src',
 'Pport_uR_TS_Location_18_plat_@platsrc',
 'Pport_uR_TS_Location_18_plat_#text',
 'Pport_uR_TS_Location_18_length',
 'Pport_uR_TS_Location_19_@tpl',
 'Pport_uR_TS_Location_19_@wta',
 'Pport_uR_TS_Location_19_@wtd',
 'Pport_uR_TS_Location_19_@pta',
 'Pport_uR_TS_Location_19_@ptd',
 'Pport_uR_TS_Location_19_arr_@et',
 'Pport_uR_TS_Location_19_arr_@src',
 'Pport_uR_TS_Location_19_dep_@et',
 'Pport_uR_TS_Location_19_dep_@src',
 'Pport_uR_TS_Location_19_plat_@platsrc',
 'Pport_uR_TS_Location_19_plat_#text',
 'Pport_uR_TS_Location_19_length',
 'Pport_uR_TS_Location_20_@tpl',
 'Pport_uR_TS_Location_20_@wta',
 'Pport_uR_TS_Location_20_@pta',
 'Pport_uR_TS_Location_20_arr_@et',
 'Pport_uR_TS_Location_20_arr_@wet',
 'Pport_uR_TS_Location_20_arr_@src',
 'Pport_uR_TS_Location_20_length',
 'Pport_uR_TS_Location_0_dep_@at',
 'Pport_uR_TS_Location_0_dep_@atClass',
 'Pport_uR_TS_Location_0_suppr',
 'Pport_uR_TS_Location_pass_@at',
 'Pport_uR_TS_Location_pass_@atClass',
 'Pport_uR_TS_Location_0_arr_@delayed',
 'Pport_uR_TS_Location_1_pass_@delayed',
 'Pport_uR_TS_Location_5_@wtp',
 'Pport_uR_TS_Location_5_pass_@et',
 'Pport_uR_TS_Location_5_pass_@src',
 'Pport_uR_TS_Location_7_@wtp',
 'Pport_uR_TS_Location_7_pass_@et',
 'Pport_uR_TS_Location_7_pass_@src',
 'Pport_uR_TS_Location_5_plat_@conf',
 'Pport_uR_TS_Location_arr_@delayed',
 'Pport_uR_TS_Location_0_pass_@at',
 'Pport_uR_TS_Location_0_pass_@atClass',
 'Pport_uR_TS_Location_2_plat_@cisPlatsup',
 'Pport_uR_TS_Location_5_plat_@cisPlatsup',
 'Pport_uR_TS_@isReverseFormation',
 'Pport_uR_TS_Location_5_pass_@delayed',
 'Pport_uR_TS_Location_6_plat_@platsup',
 'Pport_uR_TS_Location_6_plat_@cisPlatsup',
 'Pport_uR_TS_Location_7_pass_@delayed',
 'Pport_uR_TS_Location_8_@wtp',
 'Pport_uR_TS_Location_8_pass_@et',
 'Pport_uR_TS_Location_8_pass_@delayed',
 'Pport_uR_TS_Location_8_pass_@src',
 'Pport_uR_TS_Location_8_plat_@platsup',
 'Pport_uR_TS_Location_8_plat_@cisPlatsup',
 'Pport_uR_TS_Location_10_@wtp',
 'Pport_uR_TS_Location_10_pass_@et',
 'Pport_uR_TS_Location_10_pass_@delayed',
 'Pport_uR_TS_Location_10_pass_@src',
 'Pport_uR_TS_Location_11_arr_@delayed',
 'Pport_uR_TS_Location_11_dep_@wet',
 'Pport_uR_TS_Location_11_dep_@delayed',
 'Pport_uR_TS_Location_13_pass_@delayed',
 'Pport_uR_TS_Location_14_@wtp',
 'Pport_uR_TS_Location_14_pass_@et',
 'Pport_uR_TS_Location_14_pass_@delayed',
 'Pport_uR_TS_Location_14_pass_@src',
 'Pport_uR_TS_Location_15_@wtp',
 'Pport_uR_TS_Location_15_pass_@et',
 'Pport_uR_TS_Location_15_pass_@delayed',
 'Pport_uR_TS_Location_15_pass_@src',
 'Pport_uR_TS_Location_16_@wtp',
 'Pport_uR_TS_Location_16_pass_@et',
 'Pport_uR_TS_Location_16_pass_@delayed',
 'Pport_uR_TS_Location_16_pass_@src',
 'Pport_uR_TS_Location_16_plat_@platsup',
 'Pport_uR_TS_Location_16_plat_@cisPlatsup',
 'Pport_uR_TS_Location_17_@wtp',
 'Pport_uR_TS_Location_17_pass_@et',
 'Pport_uR_TS_Location_17_pass_@delayed',
 'Pport_uR_TS_Location_17_pass_@src',
 'Pport_uR_TS_Location_18_@wtp',
 'Pport_uR_TS_Location_18_pass_@et',
 'Pport_uR_TS_Location_18_pass_@delayed',
 'Pport_uR_TS_Location_18_pass_@src',
 'Pport_uR_TS_Location_19_@wtp',
 'Pport_uR_TS_Location_19_pass_@et',
 'Pport_uR_TS_Location_19_pass_@delayed',
 'Pport_uR_TS_Location_19_pass_@src',
 'Pport_uR_TS_Location_20_@wtp',
 'Pport_uR_TS_Location_20_pass_@et',
 'Pport_uR_TS_Location_20_pass_@delayed',
 'Pport_uR_TS_Location_20_pass_@src',
 'Pport_uR_TS_Location_20_plat_@platsup',
 'Pport_uR_TS_Location_20_plat_@cisPlatsup',
 'Pport_uR_TS_Location_20_plat_#text',
 'Pport_uR_TS_Location_21_@tpl',
 'Pport_uR_TS_Location_21_@wtp',
 'Pport_uR_TS_Location_21_pass_@et',
 'Pport_uR_TS_Location_21_pass_@delayed',
 'Pport_uR_TS_Location_21_pass_@src',
 'Pport_uR_TS_Location_22_@tpl',
 'Pport_uR_TS_Location_22_@wtp',
 'Pport_uR_TS_Location_22_pass_@et',
 'Pport_uR_TS_Location_22_pass_@delayed',
 'Pport_uR_TS_Location_22_pass_@src',
 'Pport_uR_TS_Location_23_@tpl',
 'Pport_uR_TS_Location_23_@wtp',
 'Pport_uR_TS_Location_23_pass_@et',
 'Pport_uR_TS_Location_23_pass_@delayed',
 'Pport_uR_TS_Location_23_pass_@src',
 'Pport_uR_TS_Location_24_@tpl',
 'Pport_uR_TS_Location_24_@wtp',
 'Pport_uR_TS_Location_24_pass_@et',
 'Pport_uR_TS_Location_24_pass_@delayed',
 'Pport_uR_TS_Location_24_pass_@src',
 'Pport_uR_TS_Location_25_@tpl',
 'Pport_uR_TS_Location_25_@wtp',
 'Pport_uR_TS_Location_25_pass_@et',
 'Pport_uR_TS_Location_25_pass_@delayed',
 'Pport_uR_TS_Location_25_pass_@src',
 'Pport_uR_TS_Location_26_@tpl',
 'Pport_uR_TS_Location_26_@wtp',
 'Pport_uR_TS_Location_26_pass_@et',
 'Pport_uR_TS_Location_26_pass_@delayed',
 'Pport_uR_TS_Location_26_pass_@src',
 'Pport_uR_TS_Location_27_@tpl',
 'Pport_uR_TS_Location_27_@wtp',
 'Pport_uR_TS_Location_27_pass_@et',
 'Pport_uR_TS_Location_27_pass_@delayed',
 'Pport_uR_TS_Location_27_pass_@src',
 'Pport_uR_TS_Location_28_@tpl',
 'Pport_uR_TS_Location_28_@wtp',
 'Pport_uR_TS_Location_28_pass_@et',
 'Pport_uR_TS_Location_28_pass_@delayed',
 'Pport_uR_TS_Location_28_pass_@src',
 'Pport_uR_TS_Location_29_@tpl',
 'Pport_uR_TS_Location_29_@wtp',
 'Pport_uR_TS_Location_29_pass_@et',
 'Pport_uR_TS_Location_29_pass_@delayed',
 'Pport_uR_TS_Location_29_pass_@src',
 'Pport_uR_TS_Location_30_@tpl',
 'Pport_uR_TS_Location_30_@wtp',
 'Pport_uR_TS_Location_30_pass_@et',
 'Pport_uR_TS_Location_30_pass_@delayed',
 'Pport_uR_TS_Location_30_pass_@src',
 'Pport_uR_TS_Location_30_plat_@platsup',
 'Pport_uR_TS_Location_30_plat_@cisPlatsup',
 'Pport_uR_TS_Location_30_plat_@platsrc',
 'Pport_uR_TS_Location_30_plat_#text',
 'Pport_uR_TS_Location_31_@tpl',
 'Pport_uR_TS_Location_31_@wtp',
 'Pport_uR_TS_Location_31_pass_@et',
 'Pport_uR_TS_Location_31_pass_@delayed',
 'Pport_uR_TS_Location_31_pass_@src',
 'Pport_uR_TS_Location_32_@tpl',
 'Pport_uR_TS_Location_32_@wtp',
 'Pport_uR_TS_Location_32_pass_@et',
 'Pport_uR_TS_Location_32_pass_@delayed',
 'Pport_uR_TS_Location_32_pass_@src',
 'Pport_uR_TS_Location_33_@tpl',
 'Pport_uR_TS_Location_33_@wtp',
 'Pport_uR_TS_Location_33_pass_@et',
 'Pport_uR_TS_Location_33_pass_@delayed',
 'Pport_uR_TS_Location_33_pass_@src',
 'Pport_uR_TS_Location_34_@tpl',
 'Pport_uR_TS_Location_34_@wta',
 'Pport_uR_TS_Location_34_@wtd',
 'Pport_uR_TS_Location_34_@pta',
 'Pport_uR_TS_Location_34_@ptd',
 'Pport_uR_TS_Location_34_arr_@et',
 'Pport_uR_TS_Location_34_arr_@wet',
 'Pport_uR_TS_Location_34_arr_@delayed',
 'Pport_uR_TS_Location_34_arr_@src',
 'Pport_uR_TS_Location_34_dep_@et',
 'Pport_uR_TS_Location_34_dep_@delayed',
 'Pport_uR_TS_Location_34_dep_@src',
 'Pport_uR_TS_Location_35_@tpl',
 'Pport_uR_TS_Location_35_@wtp',
 'Pport_uR_TS_Location_35_pass_@et',
 'Pport_uR_TS_Location_35_pass_@delayed',
 'Pport_uR_TS_Location_35_pass_@src',
 'Pport_uR_TS_Location_36_@tpl',
 'Pport_uR_TS_Location_36_@wtp',
 'Pport_uR_TS_Location_36_pass_@et',
 'Pport_uR_TS_Location_36_pass_@delayed',
 'Pport_uR_TS_Location_36_pass_@src',
 'Pport_uR_TS_Location_37_@tpl',
 'Pport_uR_TS_Location_37_@wtp',
 'Pport_uR_TS_Location_37_pass_@et',
 'Pport_uR_TS_Location_37_pass_@delayed',
 'Pport_uR_TS_Location_37_pass_@src',
 'Pport_uR_TS_Location_38_@tpl',

In [10]:
import boto3
import pandas as pd
import re
import io
import pyarrow
import pyarrow.parquet as pq
from datetime import datetime
import tempfile
import joblib
import numpy as np
import json
import pickle
from datetime import datetime
#import mlflow
import boto3
import pickle
import os
import numpy as np
import awswrangler as wr
import warnings
warnings.filterwarnings("ignore")

PROCESSED_KEYS_FILE = "tracking/processed_keys.json"

import sys
from awsglue.utils import getResolvedOptions

# Define the expected arguments
args_list = ['JOB_NAME', 'INPUT_PATH', 'OUTPUT_PATH']

# Retrieve the arguments
args = getResolvedOptions(sys.argv, args_list)

# Assign them to variables
job_name = args['JOB_NAME']
input_path = args['INPUT_PATH']
output_path = args['OUTPUT_PATH']
optional_setting = args.get('OPTIONAL_SETTING', 'default_value_if_not_provided')


import awswrangler as wr

def preprocess_for_arrival_delay(input_path, output_path):
    # Read Parquet directly from S3
    df = wr.s3.read_parquet(path=input_path)

    # Drop completely empty rows
    df = df.dropna(how='all')

    # Parse service date
    df['service_date'] = pd.to_datetime(df['Pport_uR_TS_@ssd'], errors='coerce').dt.date

    # Scheduled arrival datetime
    df['scheduled_arrival_dt'] = pd.to_datetime(
        df['service_date'].astype(str) + ' ' + df['Pport_uR_TS_Location_@wta'],
        errors='coerce'
    )

    # Actual arrival datetime
    df['actual_arrival_dt'] = pd.to_datetime(
        df['service_date'].astype(str) + ' ' + df['Pport_uR_TS_Location_arr_@at'],
        errors='coerce'
    )

    # Calculate delay
    df['arrival_delay_minutes'] = (
        df['actual_arrival_dt'] - df['scheduled_arrival_dt']
    ).dt.total_seconds() / 60.0

    df_filtered = df[(df['arrival_delay_minutes'] >= -5) &
                     (df['arrival_delay_minutes'] <= 120)].copy()

    df_filtered['day_of_week'] = pd.to_datetime(df_filtered['Pport_uR_TS_@ssd'], errors='coerce').dt.dayofweek

    # Write back to S3
    wr.s3.to_parquet(df=df_filtered, path=output_path, dataset=True, index=False)

    
# Run function with arguments from Glue
preprocess_for_arrival_delay(
    input_path=args['INPUT_PATH'],
    output_path=args['OUTPUT_PATH']
)

In [11]:
preprocess_for_arrival_delay(
    input_path="s3://darwin-raildata-mlops/wide-to-long-transformation/",
    output_path="s3://darwin-raildata-mlops/transformed-data/preprocessed-features-data/"
)

MemoryError: Unable to allocate 3.93 GiB for an array with shape (2317, 227773) and data type object

In [ ]:
import io
import joblib
import boto3
import pandas as pd
from sklearn.feature_extraction import DictVectorizer


def prepare_features(input_path, output_path, train_ratio=0.8):
    """
    Prepares features for training and validation with a flexible train/val split.
    Saves output to S3 as joblib files.
    """

    s3 = boto3.client("s3")

    # Read parquet from S3
    df = pd.read_parquet(input_path, storage_options={"anon": False})

    # Ensure required columns exist
    if 'day_of_week' not in df.columns or 'Pport_uR_TS_Location_@tpl' not in df.columns:
        raise ValueError("Missing required columns in DataFrame")

    # Train/val split
    split_index = int(len(df) * train_ratio)
    df_train = df.iloc[:split_index].copy()
    df_val = df.iloc[split_index:].copy()

    # Combined categorical feature
    df_train['day_of_week_Pport_uR_TS_Location_@tpl'] = (
        df_train['day_of_week'].astype(str) + '_' + df_train['Pport_uR_TS_Location_@tpl'].astype(str)
    )
    df_val['day_of_week_Pport_uR_TS_Location_@tpl'] = (
        df_val['day_of_week'].astype(str) + '_' + df_val['Pport_uR_TS_Location_@tpl'].astype(str)
    )

    # Vectorize
    categorical = ['day_of_week_Pport_uR_TS_Location_@tpl']
    target = 'arrival_delay_minutes'

    dv = DictVectorizer()
    X_train = dv.fit_transform(df_train[categorical].to_dict(orient='records'))
    X_val = dv.transform(df_val[categorical].to_dict(orient='records'))

    y_train = df_train[target].values
    y_val = df_val[target].values

    # Save to S3
    bucket_out, key_prefix = output_path.replace("s3://", "").split("/", 1)

    for obj, name in [
        (X_train, "X_train.joblib"),
        (y_train, "y_train.joblib"),
        (X_val, "X_val.joblib"),
        (y_val, "y_val.joblib"),
        (dv, "dict_vectorizer.joblib")
    ]:
        buffer = io.BytesIO()
        joblib.dump(obj, buffer)
        buffer.seek(0)
        s3.upload_fileobj(buffer, bucket_out, f"{key_prefix}/{name}")

    print(f"✅ Features saved to {output_path}")

    return X_train, y_train, X_val, y_val, dv

In [ ]:
X_train, y_train, X_val, y_val, dv = prepare_features(input_path = "s3://darwin-raildata-mlops/transformed-data/preprocessed-features-data/",train_ratio=0.8,output_path= "s3://darwin-raildata-mlops/feature-eng-data/")